select * from RegexMatches('',				'\s')
select * from RegexMatches(' ',				'\s')
select * from RegexMatches('ab12',			'\s')
select * from RegexMatches('123',			'\d+')
select * from RegexMatches('1',				'\d\d?')
select * from RegexMatches('12',			'\d\d?')
select * from RegexMatches('123',			'\d\d?')
select * from RegexMatches('',				'\d*')
select * from RegexMatches('123',			'\d*')
select * from RegexMatches('',				'\d+')
select * from RegexMatches('123',			'\d+')
select * from RegexMatches('ab123 #',		'\d+')
select * from RegexMatches('.123-45x6',		'\d+')
select * from RegexMatches('abc ABC 123 aB-c2-D5', '[a-zA-Z0-9-]+')
select * from RegexMatches('xx 123ab xx',	'\s*(\d+)')
select * from RegexMatches('xx 123ab xx',	'(\d+)\s*')
select * from RegexMatches('[].*+',			'\[\].\*\+')
